theme: jekyll-theme-cayman
title: 'UC Davis Bioinformatics Core September 2018 Bioinformatics Prerequisites workshop'
github:
  repository_url: https://ucdavis-bioinformatics-training.github.io/2018-September-Bioinformatics-Prerequisites
